### ISSUE TITLE
Too high outdivider limits max frequency

### ISSUE THREAD

**Issue by erikkaashoek** [pavelmc/Si5351mcu#5]
In the code is says

    if (outdivider < 6) {   // low: below 6

but this limits the max output frequency to 150 MHz with maxPLL of 900MHz.

Should it not be

    if (outdivider < 4) {   // low: below 4

**Comment by pavelmc** [comment]
Thanks for reporting it, at a glance you are right.

I will inspect the code and update it accordingly, also I will try to update some comments that speak about artifacts not in place anymore and that  will be misleading.

Cheers, Pavel.

**Comment by pavelmc** [comment]
Thanks @erikkaashoek for the bug spotting.

Indeed, after some review I found that I squashed that bug some time ago and make some little improvements in other places, but forgot to sync the changes from the dev PC to the internet!

My bad, sorry.

Bug Closed in commit 9c3cac49da31738df85d143fb4e73d85e1dc93c4
