### ISSUE TITLE
Small change enables compilation on ESP8266

### ISSUE THREAD

**Issue by ramapcsx2** [pavelmc/Si5351mcu#7]
Hey,
I just tested the library on my ESP8266 board.  
It had just one type specifier error here:  
https://github.com/pavelmc/Si5351mcu/blob/27df46781f6603ba4eaff17d39f73219f6a5b65d/src/si5351mcu.cpp#L79

Is freq supposed to be an uint32_t by chance?  
Changing it to that fixes compilation :)

**Comment by stdevPavelmc** [comment]
Thanks for spotting the issue, fix in preparation stay tuned.

**Comment by stdevPavelmc** [comment]
Fixed now, please update your libs.

fixed on commit https://github.com/pavelmc/Si5351mcu/commit/9334dbed43ddd3ba7b22c7d8669fa852cbb90f14

**Comment by pavelmc** [comment]
Issue closed
