### ISSUE TITLE
Error in Si5351mcu::setFreq() on frequency change if "omsynth[clk] == outdivider", but R changes

### ISSUE THREAD

**Issue by birdwes** [pavelmc/Si5351mcu#9]
If frequencies in steps of powers of 2 are selected, the second set of I2C writes are not executed.

To reproduce, e.g. 

setFreq( 0, 100000 )
setFreq( 0, 50000 )
setFreq( 0, 25000 )

re-reading the registers shows that the update has not taken place.  Oscilloscope readings confirm this.

Fix will be to change Si5351mcu::setFreq()

>> if (omsynth[clk] != outdivider) {

The above line needs to additionally check R value against a new cached version of that variable.

Discovered in implementing a test harness for Issue #8.

**Comment by birdwes** [comment]
Fix included in push for #8

**Comment by stdevPavelmc** [comment]
Yup, I spotted the solution while reviewing, linking this issue to the PR #10 for automatic closure.
